### PR TITLE
feat: create `Tabs` component

### LINKED ISSUE #328: Create `Tab` component
### Package / App

MAD Components

### Description

From EDS:
Screenshot 2023-12-20 at 11 15 23

### Alternatives

_No response_

### Other info

_No response_

### PR DESCRIPTION
**Pull request by HaakonSvane**
- Create `Tabs` component
- Create `TabsScreen` screen in Chronicles
- Refactor component screen navigation system
  - Fix issue where web component pages are not reloadable in web

closes #328

### CODE REVIEW

**Comment by HaakonSvane** [comment]
https://github.com/equinor/mad/assets/36899138/5cec2376-95a5-444d-bb4d-d36310f0e9fb

**Review by Sandtory — APPROVED** [review]
Ho Ho Ho! 🎅

I've reviewed your code and it looks like Santa's workshop in here - everything is in perfect order! The logic is as neat as a new year's gift wrap, and the documentation is as clear as a jingle bell! 🌟

**Review by Sandtory — DISMISSED** [review]
Ho Ho Ho! 🎅

I've reviewed your code and it looks like Santa's workshop in here - everything is in perfect order! The logic is as neat as a new year's gift wrap, and the documentation is as clear as a jingle bell! 🌟

**Comment by HaakonSvane** [comment]
Ready for re-review mr claus 🎅🏽

**Review by Sandtory — APPROVED** [review]
good tab 👍

**Pull request merged**
