### PR TITLE
fix: `.d.ts` files are now created using tsup instead of tsc

### PR DESCRIPTION
**Pull request by tormodAase**
This will help us with pull request validation, and make the tsup configs simpler

### CODE REVIEW

**Comment by tormodAase** [comment]
Looks like PR validation works 😄

**Comment by tormodAase** [comment]
Do we need changeset for this change?

**Comment by HaakonSvane** [comment]
I dont think so, as long as it seems to generate the same types

**Review by HaakonSvane — APPROVED** [review]
Good stuff 👌👌❤️

**Pull request merged**
